version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: app
    command: python /code/manage.py runserver 0.0.0.0:8000
#    command: tail -f /dev/null
    volumes:
      - ./app/src/:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db